use K_UNIVER;

SELECT DISTINCT PULPIT.PULPIT_NAME from PULPIT,FACULTY
		Where PULPIT.FACULTY = FACULTY.FACULTY and
		FACULTY.FACULTY
		in ( SELECT PROFESSION.FACULTY from PROFESSION 
		where (PROFESSION.PROFESSION_NAME Like '%технология%') or(PROFESSION.PROFESSION_NAME Like '%технологии%'));

SELECT DISTINCT PULPIT.PULPIT_NAME from PULPIT inner join FACULTY
		on PULPIT.FACULTY = FACULTY.FACULTY 
		where FACULTY.FACULTY
		in ( SELECT PROFESSION.FACULTY from PROFESSION 
		where (PROFESSION.PROFESSION_NAME Like '%технология%') or(PROFESSION.PROFESSION_NAME Like '%технологии%'));

SELECT DISTINCT PULPIT.PULPIT_NAME from PULPIT inner join FACULTY
		on PULPIT.FACULTY = FACULTY.FACULTY 
		inner join PROFESSION
		on  PROFESSION.FACULTY = FACULTY.FACULTY and ((PROFESSION.PROFESSION_NAME Like '%технология%') or(PROFESSION.PROFESSION_NAME Like '%технологии%'));

SELECT AUDITORIUM_NAME,AUDITORIUM_CAPACITY FROM AUDITORIUM a
		Where AUDITORIUM = (select top(1) AUDITORIUM from AUDITORIUM aa
			Where aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc)
															order by AUDITORIUM_CAPACITY desc;

SELECT FACULTY.FACULTY_NAME [Факультеты без кафедр] from FACULTY
		Where  exists (select * from PULPIT
							where PULPIT.FACULTY = FACULTY.FACULTY); 

SELECT top 1 
		isnull((select avg(NOTE) from PROGRESS
					where PROGRESS.[SUBJECT] like 'БД'),'0') [БД],
		isnull((select avg(NOTE) from PROGRESS
					where PROGRESS.[SUBJECT] like 'ОАиП'),'0') [ОАиП],
		isnull((select avg(NOTE) from PROGRESS
				where PROGRESS.[SUBJECT] like 'СУБД'),'0') [СУБД]
From PROGRESS;

SELECT STUDENT.IDSTUDENT, STUDENT.[NAME] from STUDENT 
		Where STUDENT.IDSTUDENT in (select PROGRESS.IDSTUDENT from PROGRESS
		Where PROGRESS.NOTE < all(select PROGRESS.NOTE from PROGRESS
								Where PROGRESS.NOTE >= 5));

SELECT STUDENT.IDSTUDENT, STUDENT.[NAME] from STUDENT 
		Where STUDENT.IDSTUDENT in (select PROGRESS.IDSTUDENT from PROGRESS
		Where PROGRESS.NOTE >= any(select PROGRESS.NOTE from PROGRESS
								Where PROGRESS.NOTE >= 9));	
								