USE [master]
GO

/****** Object:  Database [Ковалев ПРОДАЖИ]    Script Date: 04.02.2021 21:03:17 ******/
CREATE DATABASE [Ковалев ПРОДАЖИ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ковалев ПРОДАЖИ', FILENAME = N'D:\SQL Server Developer Edition 2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ковалев ПРОДАЖИ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ковалев ПРОДАЖИ_log', FILENAME = N'D:\SQL Server Developer Edition 2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ковалев ПРОДАЖИ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ковалев ПРОДАЖИ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET RECOVERY FULL 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET  MULTI_USER 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ковалев ПРОДАЖИ] SET  READ_WRITE 
GO


